# Generated by Django 5.2 on 2025-12-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Groups', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Groups',
            },
        ),
    ]
